### ISSUE TITLE
Subscriptions support

### ISSUE THREAD

**Issue by vladshcherbin** [jaydenseric/graphql-api-koa#12]
Hey 👋 

Is it possible to somehow use subscriptions?

**Comment by jaydenseric** [comment]
It's not something I've setup in any of my projects so I don't have any code examples to share, but it should be possible to use other GraphQL subscriptions solutions in combination with this package. Could the middleware be setup so if the request relates to subscriptions, the other library (or code, whatever it is) handles the request instead of `graphql-api-koa`?

I'm not really comfortable endorsing a particular strategy for subscriptions here until I've seriously immersed in the problem space and built something production quality using subscriptions. Back when subscriptions was mostly poorly maintained Apollo tech I wasn't very motivated to adopt it, but now there are a lot higher quality protocols and packages available (particularly by The Guild guys) that are more aligned with the GraphQL Foundation and the open GraphQL ecosystem.

**Comment by vladshcherbin** [comment]
I've played with a few packages, it's actually possible to quickly attach a ws server to existing graphql-api-koa one.

Small overview of findings:

- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) - most popular, has support in different client libraries, **not maintained, has a note to use another library in readme**
- [graphql-ws](https://github.com/enisdenjo/graphql-ws) - suggested one to use, has updated specs and is not compatible with above package, well maintained, has support in some client libraries
- [graphql-helix](https://github.com/contrawork/graphql-helix) - quite new, allows you to create all parts of graphql server or probably attach to existing one, has support for server-sent-events

I kinda liked `server-sent-events` idea, but support and tutorials are close to none.
In current project I have android and ios clients, both use apollo libraries which have support only for `subscriptions-transport-ws` 🤦‍♂️
For now I had to choose it with a plan to switch to `graphql-ws` once mobile libraries add support, tracking - [ios](https://github.com/apollographql/apollo-ios/issues/1622), [android](https://github.com/apollographql/apollo-android/issues/3029)

Here is a small example for reference:

websocket server in a separate file

```js
import { execute, subscribe } from 'graphql'
import { SubscriptionServer } from 'subscriptions-transport-ws'
import { schema } from './graphql'

export default function attachSubscriptionsServer(server) {
  SubscriptionServer.create(
    {
      schema,
      execute,
      subscribe
    },
    {
      server,
      path: '/subscriptions'
    }
  )
}
```

koa server

```js
import { createServer } from 'http'
import Koa from 'koa'
import router from './router'
import attachSubscriptionsServer from './websocket-server'

const app = new Koa()

app.use(router.routes())

const server = createServer(app.callback())

attachSubscriptionsServer(server)

server.listen(process.env.PORT)
```
